tabWidth: 2
printWidth: 120
singleQuote: true
arrowParens: 'avoid'
trailingComma: 'all'
jsxSingleQuote: true
bracketSpacing: false

plugins:
  - '@trivago/prettier-plugin-sort-imports'
# importの種類ごとに改行を挟まない
importOrderSeparation: false
importOrderCaseInsensitive: false
importOrder:
  - '^react$'
  - '\.css$'
  - '^@watasuke.net'
  - '<THIRD_PARTY_MODULES>'
